server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ${APPLICATION_NAME}
  main:
    banner-mode: off
  datasource:
    #url: jdbc:oracle:thin:@192.168.1.200:1521:cdb1
    #url: jdbc:oracle:thin:@localhost:1521:orcl
    url: ${ORACLE_URL}
    driver-class-name: ${ORACLE_DRIVER}
    #username: ORACLE_DEMO
    #password: dudkrish1A
    username: ${ORACLE_USER_NAME}
    password: ${ORACLE_PASSWORD}
    jpa:
      show-sql: true
      format-sql: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
      database-platform: org.hibernate.dialect.Oracle12cDialect

user:
  address:
    name: ${EMP_NAME}
    userName: ${DB_USERNAME}
    password: ${DB_PASSWORD}



