server:
  port: 8081
spring:
  application:
    name: spring-rest-oracle-k8s
  main:
    banner-mode: off
  datasource:
    #url: jdbc:oracle:thin:@192.168.1.200:1521:cdb1
    #url: jdbc:oracle:thin:@localhost:1521:orcl
    url: jdbc:oracle:thin:@192.168.1.200:1521:cdb1
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #username: ORACLE_DEMO
    #password: dudkrish1A
    username: SYSTEM
    password: dudkrish1A
    jpa:
      show-sql: true
      format-sql: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
      database-platform: org.hibernate.dialect.Oracle12cDialect

user:
  address:
    name: ${USER_NAME}



