server:
  port: 8081
spring:
  application:
    name: ${APPLICATION_NAME}
  main:
    banner-mode: off
  datasource:
    #url: jdbc:oracle:thin:@192.168.1.200:1521:cdb1
    #url: jdbc:oracle:thin:@localhost:1521:orcl
    url: ${ORACLE_URL}
    driver-class-name: ${ORACLE_DRIVER}
    #username: ORACLE_DEMO
    #password: dudkrish1A
    username: ${USER_NAME}
    password: ${PASSWORD}
    jpa:
      show-sql: ${SHOW_SQL}
      format-sql: ${FORMAT_SQL}
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
      database-platform: org.hibernate.dialect.Oracle12cDialect

user:
  address:
    name: ${EMP_NAME}



