spring:
  application:
    name: spring-rest-oracle-k8s
  main:
    banner-mode: off
    datasource:
      url: '${ORACLE_URL}'
      driver-class-name: '${DRIVER_CLASS_NAME}'
      username: '${ORACLE_USERNAME}'
      password: '${ORACLE_PASSWORD}'
      jpa:
        show-sql: true
        format-sql: true
        properties:
          hibernate:
            enable_lazy_load_no_trans: true
        database-platform: org.hibernate.dialect.Oracle12cDialect
  cloud:
    kubernetes:
      discovery:
        register: true
      secrets:
        name: oracle-secret
        namespace: spring-boot-examples

      config:
        enabled: true
        sources:
          - namespace: spring-boot-examples
            name: oracle-conf
      reload:
        enabled: true
        mode: polling
        period: 1000
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true