ALTER USER oracle_demo quota unlimited on USERS;
COMMIT;

create table Employee(
        EMP_ID             NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999,
        First_Name         VARCHAR2(10 BYTE),
        Last_Name          VARCHAR2(10 BYTE),
        Start_Date         DATE,
        End_Date           DATE,
        Salary             Number(8,2),
        City               VARCHAR2(10 BYTE),
        Description        VARCHAR2(15 BYTE)
  );
commit;

insert into Employee(EMP_ID,  First_Name, Last_Name, Start_Date,                     End_Date,                       Salary,  City,       Description)
values ('01','Jason',    'Martin',  to_date('19960725','YYYYMMDD'), to_date('20060725','YYYYMMDD'), 1234.56, 'Toronto',  'Programmer');
insert into Employee(EMP_ID,  First_Name, Last_Name, Start_Date,                     End_Date,                       Salary,  City,       Description)
values('02','Alison',   'Mathews', to_date('19760321','YYYYMMDD'), to_date('19860221','YYYYMMDD'), 6661.78, 'Vancouver','Tester');
insert into Employee(EMP_ID,  First_Name, Last_Name, Start_Date,                     End_Date,                       Salary,  City,       Description)
values('03','James',    'Smith',   to_date('19781212','YYYYMMDD'), to_date('19900315','YYYYMMDD'), 6544.78, 'Vancouver','Tester');
insert into Employee(EMP_ID,  First_Name, Last_Name, Start_Date,                     End_Date,                       Salary,  City,       Description)
values('04','Celia',    'Rice',    to_date('19821024','YYYYMMDD'), to_date('19990421','YYYYMMDD'), 2344.78, 'Vancouver','Manager');
insert into Employee(EMP_ID,  First_Name, Last_Name, Start_Date,                     End_Date,                       Salary,  City,       Description)
values('05','Robert',   'Black',   to_date('19840115','YYYYMMDD'), to_date('19980808','YYYYMMDD'), 2334.78, 'Vancouver','Tester');
insert into Employee(EMP_ID,  First_Name, Last_Name, Start_Date,                     End_Date,                       Salary, City,        Description)
values('06','Linda',    'Green',   to_date('19870730','YYYYMMDD'), to_date('19960104','YYYYMMDD'), 4322.78,'New York',  'Tester');
insert into Employee(EMP_ID,  First_Name, Last_Name, Start_Date,                     End_Date,                       Salary, City,        Description)
values('07','David',    'Larry',   to_date('19901231','YYYYMMDD'), to_date('19980212','YYYYMMDD'), 7897.78,'New York',  'Manager');
insert into Employee(EMP_ID,  First_Name, Last_Name, Start_Date,                     End_Date,                       Salary, City,        Description)
values('08','James',    'Cat',     to_date('19960917','YYYYMMDD'), to_date('20020415','YYYYMMDD'), 1232.78,'Vancouver', 'Tester');

SELECT * FROM Employee;

create sequence student_sequence;

CREATE OR REPLACE PROCEDURE AddNewEmployee (
    p_FirstName  employee.first_name%TYPE,
    p_LastName   employee.last_name%TYPE,
    p_Salary      employee.salary%TYPE) AS
BEGIN
    INSERT INTO employee (EMP_ID, first_name, last_name,salary)
    VALUES (student_sequence.nextval, p_FirstName, p_LastName,p_Salary);
    COMMIT;
END AddNewEmployee;


CREATE TABLE ORACLE_DEMO.COUNTRIES (
"COUNTRY_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999
INCREMENT BY 1 START WITH 1 CACHE 20,
"COUNTRY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
"ALPHA2" CHAR(2 BYTE),
"ALPHA3" CHAR(3 BYTE),
"COUNTRY_CODE" NUMBER(10,0),
"REGION" VARCHAR2(100 BYTE),
"SUB_REGION" VARCHAR2(100 BYTE),
"INTERMEDIATE_REGION" VARCHAR2(100 BYTE),
"REGION_CODE" NUMBER(10,0),
"SUB_REGION_CODE" NUMBER(10,0),
"INTERMEDIATE_REGION_CODE" NUMBER(10,0),
CONSTRAINT "COUNTRY_ID_PK" PRIMARY KEY ("COUNTRY_ID")
);

