apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-pvc
spec:
  volumeName: spring-demo-pv
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi