#kubectl get deploy -o wide
#kubectl get pod -o wide
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: spring-boot-oracle-k8s
  labels:
    app: spring-deployment-app
spec:
  replicas: 1
  template:
    metadata:
      name: spring-pod
      labels:
        app: spring-deployment-app
    spec:
      containers:
        - name: spring-container
          image: harilearning1989/spring-boot-oracle-k8s:13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: EMP_NAME
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: emp-name
            - name: APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: application-name
            - name: ORACLE_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: oracle-url
            - name: ORACLE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: oracle-driver
            - name: USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: user-name
            - name: PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: password
      restartPolicy: Always
  selector:
    matchLabels:
      app: spring-deployment-app
