apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-helloworld
  name: nginx-helloworld
  namespace: spring-boot-oracle-k8s
spec:
  containers:
    - image: nginx
      name: nginx-helloworld
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr"
          name: www-data
  initContainers:
    - name: git-cloner
      image: alpine/git
      args:
        - clone
        - --single-branch
        - --
        - https://github.com/harilearning1989/DataFiles.git
        - /data
      volumeMounts:
        - mountPath: /data
          name: www-data
  volumes:
    - name: www-data
      emptyDir: {}