apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: spring-boot-oracle-k8s
data:
  password: cGFzc3dvcmQ=
  username: cm9vdA==
  oracle-user-name: U1lTVEVN
  oracle-password: ZHVka3Jpc2gxQQ==